### ISSUE TITLE
Rename "Requests" to "Needs"

### ISSUE THREAD

**Issue by Tolkiennerd** [Tolkiennerd/UnhousedOutreach#21]
The site currently lists any necessities a housing insecure neighbor has as "requests." Any references to "requests" (in this context) should be renamed to "needs". The database column, queries, variable names, API endpoints, and all other references should be renamed to "needs". Some references (particularly those on the UI) have already been renamed.

**Comment by rhodesconover1** [comment]
Ammaarah and I have produced a change set that we believe meets the requirements of this issue. I have staged them on a personal branch but discovered that I am unable to push this branch at this time. Once that is resolved (I've been in contact with Matthew about it), I will create a merge request and seek review.

**Comment by rhodesconover1** [comment]
The associated MR has been completed. This issue can be closed! :)
